import "./globals.css";
import type { Metadata } from "next";
import ApolloWrapper from "@/app/_lib/apollo-wrapper";
import RecoilWrapper from "../_lib/recoil-wrapper";
import Navigation from "../_components/Navigation";

export const metadata: Metadata = {
  title: "Authentic Japanese Food Deliveroo",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className="container mx-auto px-4">
      <ApolloWrapper>
        <RecoilWrapper>
          <Navigation />
          <div className="mx-auto px-4">{children}</div>
        </RecoilWrapper>
      </ApolloWrapper>
    </body>
  </html>
);

export default RootLayout;
